import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :brain_cloud_web, BrainCloudWeb.Endpoint,
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :brain_cloud_web, BrainCloudWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

config :brain_cloud_web, :session_options,
  store: :cookie,
  key: "_brain_cloud_web_session",
  signing_salt: "browser-signing-v1",
  encryption_salt: "browser-encryption-v1",
  same_site: "Lax",
  max_age: 14 * 24 * 60 * 60,
  http_only: true,
  secure: true

# Emit machine-readable logs in production.
config :logger,
  level: :info,
  default_handler: [
    formatter:
      {LoggerJSON.Formatters.Basic,
       metadata: [:request_id, :method, :path, :status, :duration_ms]}
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
